/* vocab-1.js
   Global vocab payload for 閃卡
   Schema: window.VOCAB = { lessons: { "Lesson 1-1": [...], ... } }
   Each item: { en, trad, simp, py }
*/
window.VOCAB = {
  lessons: {
    // ---- 1-1 ----
    "Lesson 1-1": [
      {en:"you", trad:"你", simp:"你", py:"nǐ"},
      {en:"good; well", trad:"好", simp:"好", py:"hǎo"},
      {en:"to be; yes (affirmative)", trad:"是", simp:"是", py:"shì"},
      {en:"student", trad:"學生", simp:"学生", py:"xuéshēng"},
      {en:"teacher", trad:"老師", simp:"老师", py:"lǎoshī"},
      {en:"I; me", trad:"我", simp:"我", py:"wǒ"},
      {en:"also; too", trad:"也", simp:"也", py:"yě"},
      {en:"not; no", trad:"不", simp:"不", py:"bù"},
      {en:"he; him", trad:"他", simp:"他", py:"tā"},
      {en:"she; her", trad:"她", simp:"她", py:"tā"},
      {en:"(yes/no question particle)", trad:"嗎", simp:"吗", py:"ma"},
      {en:"(sentence particle: and you?)", trad:"呢", simp:"呢", py:"ne"}
    ],

    // ---- 1-2 (Names & basic classroom language) ----
    "Lesson 1-2": [
      {en:"(polite) you", trad:"您", simp:"您", py:"nín"},
      {en:"honored; expensive", trad:"貴", simp:"贵", py:"guì"},
      {en:"surname; be surnamed", trad:"姓", simp:"姓", py:"xìng"},
      {en:"may I ask; (polite) please", trad:"請問", simp:"请问", py:"qǐngwèn"},
      {en:"(structural particle)", trad:"的", simp:"的", py:"de"},
      {en:"English (language)", trad:"英文", simp:"英文", py:"Yīngwén"},
      {en:"name", trad:"名字", simp:"名字", py:"míngzi"},
      {en:"Chinese (language)", trad:"中文", simp:"中文", py:"Zhōngwén"},
      {en:"to be called; to call", trad:"叫", simp:"叫", py:"jiào"},
      {en:"what", trad:"什麼", simp:"什么", py:"shénme"},
      {en:"she; her", trad:"她", simp:"她", py:"tā"},
      {en:"who; whom", trad:"誰", simp:"谁", py:"shéi / shuí"},
      {en:"classmate", trad:"同學", simp:"同学", py:"tóngxué"}
    ],

    // ---- 1-3 (Nationalities & languages) ----
    "Lesson 1-3": [
      {en:"which", trad:"哪", simp:"哪", py:"nǎ / něi"},
      {en:"country", trad:"國", simp:"国", py:"guó"},
      {en:"person; people", trad:"人", simp:"人", py:"rén"},
      {en:"very; quite", trad:"很", simp:"很", py:"hěn"},
      {en:"by the way", trad:"對了", simp:"对了", py:"duìle"},
      {en:"France", trad:"法國", simp:"法国", py:"Fǎguó"},
      {en:"United States", trad:"美國", simp:"美国", py:"Měiguó"},
      {en:"Britain", trad:"英國", simp:"英国", py:"Yīngguó"},
      {en:"China", trad:"中國", simp:"中国", py:"Zhōngguó"},
      {en:"to speak; say", trad:"說", simp:"说", py:"shuō"},
      {en:"can; know how to", trad:"會", simp:"会", py:"huì"},
      {en:"a little (retroflex)", trad:"一點兒", simp:"一点儿", py:"yìdiǎnr"},
      {en:"French (language)", trad:"法文", simp:"法文", py:"Fǎwén"},
      {en:"and", trad:"和", simp:"和", py:"hé"}
    ],

    // ---- 1-4 (Studies) ----
    "Lesson 1-4": [
      {en:"that", trad:"那", simp:"那", py:"nà / nèi"},
      {en:"book", trad:"書", simp:"书", py:"shū"},
      {en:"this", trad:"這", simp:"这", py:"zhè / zhèi"},
      {en:"(M.W. for books) volume", trad:"本", simp:"本", py:"běn"},
      {en:"literature", trad:"文學", simp:"文学", py:"wénxué"},
      {en:"engineering", trad:"工程", simp:"工程", py:"gōngchéng"},
      {en:"difficult", trad:"難", simp:"难", py:"nán"},
      {en:"too; excessively", trad:"太", simp:"太", py:"tài"},
      {en:"but; however", trad:"可是", simp:"可是", py:"kěshì"},
      {en:"homework; assignment", trad:"功課", simp:"功课", py:"gōngkè"},
      {en:"many; much", trad:"多", simp:"多", py:"duō"},
      {en:"we; us", trad:"我們", simp:"我们", py:"wǒmen"},
      {en:"few; little", trad:"少", simp:"少", py:"shǎo"}
    ],

    // ---- 1-5 (Introductions) ----
    "Lesson 1-5": [
      {en:"friend", trad:"朋友", simp:"朋友", py:"péngyou"},
      {en:"to come", trad:"來", simp:"来", py:"lái"},
      {en:"to introduce; introduction", trad:"介紹", simp:"介绍", py:"jièshào"},
      {en:"(after verb) briefly", trad:"一下", simp:"一下", py:"yíxià"},
      {en:"roommate", trad:"室友", simp:"室友", py:"shìyǒu"},
      {en:"to have; there is/are", trad:"有", simp:"有", py:"yǒu"},
      {en:"how many", trad:"幾", simp:"几", py:"jǐ"},
      {en:"two (before M.W.)", trad:"兩", simp:"两", py:"liǎng"},
      {en:"(general M.W.)", trad:"個", simp:"个", py:"gè"},
      {en:"all; both", trad:"都", simp:"都", py:"dōu"},
      {en:"often; frequently", trad:"常", simp:"常", py:"cháng"},
      {en:"with", trad:"跟", simp:"跟", py:"gēn"}
    ],

    // ---- 1-6 (Family) ----
    "Lesson 1-6": [
      {en:"home; family", trad:"家", simp:"家", py:"jiā"},
      {en:"everyone", trad:"大家", simp:"大家", py:"dàjiā"},
      {en:"from", trad:"從", simp:"从", py:"cóng"},
      {en:"to be at; to be in", trad:"在", simp:"在", py:"zài"},
      {en:"one", trad:"一", simp:"一", py:"yī"},
      {en:"four", trad:"四", simp:"四", py:"sì"},
      {en:"father", trad:"爸爸", simp:"爸爸", py:"bàba"},
      {en:"mother", trad:"媽媽", simp:"妈妈", py:"māma"},
      {en:"elder sister", trad:"姊姊", simp:"姐姐", py:"jiějie"},
      {en:"job; to work", trad:"工作", simp:"工作", py:"gōngzuò"},
      {en:"engineer", trad:"工程師", simp:"工程师", py:"gōngchéngshī"},
      {en:"boyfriend", trad:"男朋友", simp:"男朋友", py:"nánpéngyou"},
      {en:"male", trad:"男", simp:"男", py:"nán"},
      {en:"to not have; without", trad:"沒有", simp:"没有", py:"méiyǒu"},
      {en:"(M.W. vehicles)", trad:"輛", simp:"辆", py:"liàng"},
      {en:"car", trad:"車", simp:"车", py:"chē"},
      {en:"(M.W. for some animals/one of a pair)", trad:"隻", simp:"只", py:"zhī"},
      {en:"dog", trad:"狗", simp:"狗", py:"gǒu"},
      {en:"to love", trad:"愛", simp:"爱", py:"ài"}
    ],

    // ---- 1-7 (Addresses & numbers) ----
    "Lesson 1-7": [
      {en:"to live", trad:"住", simp:"住", py:"zhù"},
      {en:"where", trad:"哪兒", simp:"哪儿", py:"nǎr"},
      {en:"dorm", trad:"宿舍", simp:"宿舍", py:"sùshè"},
      {en:"how many; how much", trad:"多少", simp:"多少", py:"duōshǎo"},
      {en:"number", trad:"號", simp:"号", py:"hào"},
      {en:"room", trad:"房間", simp:"房间", py:"fángjiān"},
      {en:"big", trad:"大", simp:"大", py:"dà"},
      {en:"phone", trad:"電話", simp:"电话", py:"diànhuà"},
      {en:"small", trad:"小", simp:"小", py:"xiǎo"},
      {en:"number (serial) ", trad:"號碼", simp:"号码", py:"hàomǎ"},
      {en:"two", trad:"二", simp:"二", py:"èr"},
      {en:"three", trad:"三", simp:"三", py:"sān"},
      {en:"five", trad:"五", simp:"五", py:"wǔ"},
      {en:"six", trad:"六", simp:"六", py:"liù"},
      {en:"seven", trad:"七", simp:"七", py:"qī"},
      {en:"eight", trad:"八", simp:"八", py:"bā"},
      {en:"nine", trad:"九", simp:"九", py:"jiǔ"},
      {en:"cell phone", trad:"手機", simp:"手机", py:"shǒujī"},
      {en:"off campus", trad:"校外", simp:"校外", py:"xiàowài"}
    ],

    // ---- 1-8 (Meeting & Making Plans) ----
    "Lesson 1-8": [
      {en:"to know; recognize; be acquainted/familiar with", trad:"認識", simp:"认识", py:"rènshi"},
      {en:"to go", trad:"去", simp:"去", py:"qù"},
      {en:"to attend class; class, lesson", trad:"上課", simp:"上课", py:"shàngkè"},
      {en:"to end class; class dismissed", trad:"下課", simp:"下课", py:"xiàkè"},
      {en:"after; afterwards; later", trad:"以後", simp:"以后", py:"yǐhòu"},
      {en:"matter; thing; business", trad:"事", simp:"事", py:"shì"},
      {en:"to want; to think; to miss", trad:"想", simp:"想", py:"xiǎng"},
      {en:"to return", trad:"回", simp:"回", py:"huí"},
      {en:"together", trad:"一起", simp:"一起", py:"yìqǐ"},
      {en:"to eat; to have a meal", trad:"吃飯", simp:"吃饭", py:"chīfàn"},
      {en:"to eat", trad:"吃", simp:"吃", py:"chī"},
      {en:"cooked rice; meal", trad:"飯", simp:"饭", py:"fàn"},
      {en:"dish; cuisine", trad:"菜", simp:"菜", py:"cài"},
      {en:"today", trad:"今天", simp:"今天", py:"jīntiān"},
      {en:"next time", trad:"下次", simp:"下次", py:"xiàcì"},
      {en:"how is it; how about it", trad:"怎麼樣", simp:"怎么样", py:"zěnmeyàng"},
      {en:"to be all right; be okay", trad:"行", simp:"行", py:"xíng"},
      {en:"good-bye; see you again", trad:"再見", simp:"再见", py:"zàijiàn"},
      {en:"to see", trad:"見", simp:"见", py:"jiàn"}
    ],

    // ---- 1-9 (Phone Calls) ----
    "Lesson 1-9": [
      {en:"(in the process of)", trad:"正在", simp:"正在", py:"zhèngzài"},
      {en:"to make a phone call", trad:"打電話", simp:"打电话", py:"dǎ diànhuà"},
      {en:"to hit; to call; to make", trad:"打", simp:"打", py:"dǎ"},
      {en:"hello/hey (on the phone)", trad:"喂", simp:"喂", py:"wèi"},
      {en:"to wait a moment; hang on", trad:"等一下兒", simp:"等一下儿", py:"děng yíxiàr"},
      {en:"to wait", trad:"等", simp:"等", py:"děng"},
      {en:"Got it.", trad:"知道了", simp:"知道了", py:"zhīdao le"},
      {en:"to know; be aware of", trad:"知道", simp:"知道", py:"zhīdao"},
      {en:"thanks", trad:"謝謝", simp:"谢谢", py:"xièxie"},
      {en:"(suggestion/assumption particle)", trad:"吧", simp:"吧", py:"ba"},
      {en:"correct; right", trad:"對", simp:"对", py:"duì"},
      {en:"busy", trad:"忙", simp:"忙", py:"máng"},
      {en:"to look at; to see; to watch", trad:"看", simp:"看", py:"kàn"},
      {en:"television", trad:"電視", simp:"电视", py:"diànshì"},
      {en:"to do", trad:"做", simp:"做", py:"zuò"},
      {en:"to be online", trad:"上網", simp:"上网", py:"shàngwǎng"},
      {en:"(on the phone) this is … speaking", trad:"我就是", simp:"我就是", py:"wǒ jiù shì"},
      {en:"(polite M.W. for people)", trad:"位", simp:"位", py:"wèi"},
      {en:"to leave a message (Mainland)", trad:"留言", simp:"留言", py:"liúyán"},
      {en:"to leave a message (also TW)", trad:"留話", simp:"留话", py:"liúhuà"},
      {en:"I’m sorry", trad:"對不起", simp:"对不起", py:"duìbuqǐ"},
      {en:"when; at what time", trad:"什麼時候", simp:"什么时候", py:"shénme shíhòu"},
      {en:"to return", trad:"回來", simp:"回来", py:"huílái"},
      {en:"evening; night", trad:"晚上", simp:"晚上", py:"wǎnshang"},
      {en:"to want; to desire", trad:"要", simp:"要", py:"yào"},
      {en:"to; for; to give", trad:"給", simp:"给", py:"gěi"}
    ],

    // ---- 1-10 (Time & Schedules) ----
    "Lesson 1-10": [
      {en:"every day", trad:"每天", simp:"每天", py:"měitiān"},
      {en:"every", trad:"每", simp:"每", py:"měi"},
      {en:"day", trad:"天", simp:"天", py:"tiān"},
      {en:"half", trad:"半", simp:"半", py:"bàn"},
      {en:"to get up", trad:"起床", simp:"起床", py:"qǐchuáng"},
      {en:"college; university", trad:"大學", simp:"大学", py:"dàxué"},
      {en:"life", trad:"生活", simp:"生活", py:"shēnghuó"},
      {en:"semester", trad:"學期", simp:"学期", py:"xuéqī"},
      {en:"(M.W. for courses)", trad:"門", simp:"门", py:"mén"},
      {en:"o’clock (on clock)", trad:"點", simp:"点", py:"diǎn"},
      {en:"to sleep; go to bed", trad:"睡覺", simp:"睡觉", py:"shuìjiào"},
      {en:"as early as; precisely", trad:"就", simp:"就", py:"jiù"},
      {en:"not until; only then", trad:"才", simp:"才", py:"cái"},
      {en:"a quarter (of an hour)", trad:"刻", simp:"刻", py:"kè"},
      {en:"then; afterwards", trad:"然後", simp:"然后", py:"ránhòu"},
      {en:"library", trad:"圖書館", simp:"图书馆", py:"túshūguǎn"},
      {en:"afternoon", trad:"下午", simp:"下午", py:"xiàowǔ"},
      {en:"to like", trad:"喜歡", simp:"喜欢", py:"xǐhuan"},
      {en:"to play ball (sports)", trad:"打球", simp:"打球", py:"dǎqiú"},
      {en:"ball", trad:"球", simp:"球", py:"qiú"},
      {en:"to write", trad:"寫", simp:"写", py:"xiě"},
      {en:"letter", trad:"信", simp:"信", py:"xìn"},
      {en:"email", trad:"電子郵件", simp:"电子邮件", py:"diànzǐ yóujiàn"},
      {en:"address", trad:"地址", simp:"地址", py:"dìzhǐ"},
      {en:"year", trad:"年", simp:"年", py:"nián"},
      {en:"month", trad:"月", simp:"月", py:"yuè"},
      {en:"day (date/weekday word)", trad:"日", simp:"日", py:"rì"}
    ],

    // ---- 1-11 (Ordering Food) ----
    "Lesson 1-11": [
      {en:"red", trad:"紅", simp:"红", py:"hóng"},
      {en:"tea", trad:"茶", simp:"茶", py:"chá"},
      {en:"or (A or B?)", trad:"還是", simp:"还是", py:"háishi"},
      {en:"still; also", trad:"還", simp:"还", py:"hái"},
      {en:"green", trad:"綠", simp:"绿", py:"lǜ"},
      {en:"waiter/waitress", trad:"服務員", simp:"服务员", py:"fúwùyuán"},
      {en:"to sit", trad:"坐", simp:"坐", py:"zuò"},
      {en:"Miss", trad:"小姐", simp:"小姐", py:"xiǎojiě"},
      {en:"Mister", trad:"先生", simp:"先生", py:"xiānsheng"},
      {en:"first", trad:"先", simp:"先", py:"xiān"},
      {en:"to drink", trad:"喝", simp:"喝", py:"hē"},
      {en:"cup (M.W.)", trad:"杯", simp:"杯", py:"bēi"},
      {en:"ice; iced; with ice", trad:"冰", simp:"冰", py:"bīng"},
      {en:"water", trad:"水", simp:"水", py:"shuǐ"},
      {en:"bottle (M.W.)", trad:"瓶", simp:"瓶", py:"píng"},
      {en:"cola", trad:"可樂", simp:"可乐", py:"kělè"},
      {en:"noodle", trad:"麵", simp:"面", py:"miàn"},
      {en:"dumpling (crescent-shaped)", trad:"餃子", simp:"饺子", py:"jiǎozi"},
      {en:"plate (M.W.)", trad:"盤", simp:"盘", py:"pán"},
      {en:"to stir-fry", trad:"炒", simp:"炒", py:"chǎo"},
      {en:"ten", trad:"十", simp:"十", py:"shí"},
      {en:"to order food", trad:"點菜", simp:"点菜", py:"diǎncài"},
      {en:"bowl (M.W.)", trad:"碗", simp:"碗", py:"wǎn"},
      {en:"soup", trad:"湯", simp:"汤", py:"tāng"},
      {en:"pair (M.W.)", trad:"雙", simp:"双", py:"shuāng"},
      {en:"chopstick", trad:"筷子", simp:"筷子", py:"kuàizi"}
    ],

    // ---- 1-18 (Core Vocab you approved) ----
    "Lesson 1-18": [
      {en:"train", trad:"火車", simp:"火车", py:"huǒchē"},
      {en:"to travel", trad:"旅行", simp:"旅行", py:"lǚxíng"},
      {en:"to be away from", trad:"離", simp:"离", py:"lí"},
      {en:"school", trad:"學校", simp:"学校", py:"xuéxiào"},
      {en:"far", trad:"遠", simp:"远", py:"yuǎn"},
      {en:"only", trad:"只要", simp:"只要", py:"zhǐyào"},
      {en:"minute", trad:"分鐘", simp:"分钟", py:"fēnzhōng"},
      {en:"to ride", trad:"騎", simp:"骑", py:"qí"},
      {en:"bicycle", trad:"自行車", simp:"自行车", py:"zìxíngchē"},
      {en:"bus", trad:"公共汽車", simp:"公共汽车", py:"gōnggòngqìchē"},
      {en:"to walk", trad:"走路", simp:"走路", py:"zǒulù"},
      {en:"road", trad:"路", simp:"路", py:"lù"},
      {en:"near", trad:"近", simp:"近", py:"jìn"},
      {en:"the West", trad:"西部", simp:"西部", py:"xībù"},
      {en:"first", trad:"先", simp:"先", py:"xiān"},
      {en:"scenery", trad:"風景", simp:"风景", py:"fēngjǐng"},
      {en:"ship", trad:"船", simp:"船", py:"chuán"},
      {en:"the South", trad:"南部", simp:"南部", py:"nánbù"},
      {en:"to hear of / it is said", trad:"聽說", simp:"听说", py:"tīngshuō"},
      {en:"to hear", trad:"聽", simp:"听", py:"tīng"},
      {en:"seaside", trad:"海邊", simp:"海边", py:"hǎibiān"},
      {en:"scenery, view", trad:"景色", simp:"景色", py:"jǐngsè"},
      {en:"altogether, in all", trad:"一共", simp:"一共", py:"yígòng"},
      {en:"to rent; lease", trad:"租", simp:"租", py:"zū"}
    ],
    
    // ---- 1-19 (Health & Medicine) ----
    "Lesson 1-19": [
      { en:"cold, flu",                  trad:"感冒", simp:"感冒", py:"gǎnmào" },
      { en:"hungry; to starve",          trad:"餓",   simp:"饿",   py:"è" },
      { en:"what happened; what's wrong",trad:"怎麼了", simp:"怎么了", py:"zěnmele" },
      { en:"to be like; to seem",        trad:"好像", simp:"好像", py:"hǎoxiàng" },
      { en:"comfortable; well",          trad:"舒服", simp:"舒服", py:"shūfu" },
      { en:"to have a headache",         trad:"頭疼", simp:"头疼", py:"tóuténg" },   // first word only
      { en:"to have a fever",            trad:"發燒", simp:"发烧", py:"fāshāo" },
      { en:"to cough",                   trad:"咳嗽", simp:"咳嗽", py:"késou" },
      { en:"to fall ill; get sick",      trad:"生病", simp:"生病", py:"shēngbìng" }, // first word only
      { en:"exam",                       trad:"考試", simp:"考试", py:"kǎoshì" },
      { en:"to review",                  trad:"復習", simp:"复习", py:"fùxí" },
      { en:"therefore; consequently",    trad:"所以", simp:"所以", py:"suǒyǐ" },
      { en:"doctor",                     trad:"醫生", simp:"医生", py:"yīshēng" },
      { en:"to take medicine",           trad:"吃藥", simp:"吃药", py:"chīyào" },    // first word only
      { en:"(particle de)",              trad:"地",   simp:"地",   py:"de" },
      { en:"to rest",                    trad:"休息", simp:"休息", py:"xiūxi" },
      { en:"to prepare",                 trad:"準備", simp:"准备", py:"zhǔnbèi" },
      { en:"notes",                      trad:"筆記", simp:"笔记", py:"bǐjì" },
      { en:"to thank; to be grateful",   trad:"感謝", simp:"感谢", py:"gǎnxiè" },
      { en:"to deliver; escort; see off",trad:"送",   simp:"送",   py:"sòng" }
    ],

// ---- 1-20 (Renting an Apartment) ----
    "Lesson 1-20": [
      {en:"(introduces the object of a verb)", trad:"把",   simp:"把",   py:"bǎ"},
      {en:"to bring over",                    trad:"帶來", simp:"带来", py:"dàilái"},
      {en:"(sentence-final particle indicating surprise)", trad:"啊", simp:"啊", py:"a"},
      {en:"to move",                          trad:"搬",   simp:"搬",   py:"bān"},
      {en:"to be out",                        trad:"出",   simp:"出",   py:"chū"},
      {en:"to go out",                        trad:"出去", simp:"出去", py:"chūqù"},
      {en:"to come over",                     trad:"過來", simp:"过来", py:"guòlái"},
      {en:"to cook",                          trad:"做飯", simp:"做饭", py:"zuòfàn"},
      {en:"no problem",                       trad:"沒關係", simp:"没关系", py:"méiguānxi"},
      {en:"before; previously",               trad:"以前", simp:"以前", py:"yǐqián"},
      {en:"but",                              trad:"但是", simp:"但是", py:"dànshì"},
      {en:"girlfriend",                       trad:"女朋友", simp:"女朋友", py:"nǚpéngyou"},
      {en:"must",                             trad:"必須", simp:"必须", py:"bìxū"},
      {en:"first day",                        trad:"第一天", simp:"第一天", py:"dìyītiān"},
      {en:"prefix indicating an ordinal number", trad:"第", simp:"第", py:"dì"},
      {en:"to pay",                           trad:"付",   simp:"付",   py:"fù"},
      {en:"rent",                             trad:"房租", simp:"房租", py:"fángzū"},
      {en:"upstairs",                         trad:"樓上", simp:"楼上", py:"lóushàng"},
      {en:"immediately",                      trad:"馬上", simp:"马上", py:"mǎshàng"}
    ],

// ---- 1-21 (Future Plans) ----
"Lesson 1-21": [
  {en:"summer vacation", trad:"暑假", simp:"暑假", py:"shǔjià"},
  {en:"to graduate", trad:"畢業", simp:"毕业", py:"bìyè"},
  {en:"to decide", trad:"決定", simp:"决定", py:"juédìng"},
  {en:"perhaps; maybe; possibly", trad:"可能", simp:"可能", py:"kěnéng"},
  {en:"to apply", trad:"申請", simp:"申请", py:"shēnqǐng"},
  {en:"graduate school", trad:"研究生院", simp:"研究生院", py:"yánjiūshēngyuàn"},
  {en:"to research; to study/examine", trad:"研究", simp:"研究", py:"yánjiū"},
  {en:"overseas; abroad", trad:"國外", simp:"国外", py:"guówài"},
  {en:"to study abroad", trad:"留學", simp:"留学", py:"liúxué"},
  {en:"to seek; to look for", trad:"找", simp:"找", py:"zhǎo"},
  {en:"to work for others; to be employed", trad:"打工", simp:"打工", py:"dǎgōng"},
  {en:"(M.W. for companies, enterprises, stores)", trad:"家", simp:"家", py:"jiā"},
  {en:"company", trad:"公司", simp:"公司", py:"gōngsī"},
  {en:"internship; to practice; to intern", trad:"實習", simp:"实习", py:"shíxí"},
  {en:"computer", trad:"電腦", simp:"电脑", py:"diànnǎo"},
  {en:"summer vacation (term)", trad:"暑期", simp:"暑期", py:"shǔqī"},
  {en:"class", trad:"班", simp:"班", py:"bān"},
  {en:"at the same time", trad:"一面", simp:"一面", py:"yīmiàn"},
  {en:"interesting; enjoyable", trad:"有意思", simp:"有意思", py:"yǒuyìsi"},
  {en:"happy", trad:"愉快", simp:"愉快", py:"yúkuài"},
  {en:"have a pleasant journey", trad:"一路平安", simp:"一路平安", py:"yílùpíng’ān"},
  {en:"good luck", trad:"好運", simp:"好运", py:"hǎoyùn"}
],

// ---- 1-22 (Arts and Culture) ----
"Lesson 1-22": [
  {en:"because", trad:"因為", simp:"因为", py:"yīnwèi"},
  {en:"but; however", trad:"不過", simp:"不过", py:"búguò"},
  {en:"conscientious; serious", trad:"認真", simp:"认真", py:"rènzhēn"},
  {en:"already", trad:"已經", simp:"已经", py:"yǐjīng"},
  {en:"beautiful", trad:"美麗", simp:"美丽", py:"měilì"},
  {en:"city", trad:"城市", simp:"城市", py:"chéngshì"},
  {en:"everywhere", trad:"到處", simp:"到处", py:"dàochù"},
  {en:"new", trad:"新", simp:"新", py:"xīn"},
  {en:"some", trad:"一些", simp:"一些", py:"yìxiē"},
  {en:"place", trad:"地方", simp:"地方", py:"dìfāng"},
  {en:"activity", trad:"活動", simp:"活动", py:"huódòng"},
  {en:"for example", trad:"比如", simp:"比如", py:"bǐrú"},
  {en:"Peking Opera", trad:"京劇", simp:"京剧", py:"jīngjù"},
  {en:"calligraphy", trad:"書法", simp:"书法", py:"shūfǎ"},
  {en:"et cetera", trad:"等等", simp:"等等", py:"děngděng"},
  {en:"thing", trad:"東西", simp:"东西", py:"dōngxi"},
  {en:"little steamed buns with stuffing", trad:"小籠包", simp:"小笼包", py:"xiǎolóngbāo"},
  {en:"opportunity", trad:"機會", simp:"机会", py:"jīhuì"},
  {en:"to have a taste", trad:"嚐嚐", simp:"尝尝", py:"chángchang"},
  {en:"to start; to begin", trad:"開始", simp:"开始", py:"kāishǐ"},
  {en:"happy", trad:"高興", simp:"高兴", py:"gāoxìng"},
  {en:"to receive", trad:"收到", simp:"收到", py:"shōudào"},
  {en:"it seems", trad:"看來", simp:"看来", py:"kànlái"},
  {en:"happy", trad:"開心", simp:"开心", py:"kāixīn"},
  {en:"colleague; co-worker", trad:"同事", simp:"同事", py:"tóngshì"},
  {en:"warm-hearted", trad:"熱心", simp:"热心", py:"rèxīn"},
  {en:"boss", trad:"老闆", simp:"老板", py:"lǎobǎn"},
  {en:"to learn; to master", trad:"學到", simp:"学到", py:"xuédào"},
  {en:"to write a letter (to the speaker)", trad:"來信", simp:"来信", py:"láixìn"},
    {en:"to take care", trad:"保重", simp:"保重", py:"bǎozhòng"}
],

// ---- 2-1 (Moving to a New Place) ----
"Lesson 2-1": [
  {en:"to move backwards; to reverse", trad:"倒", simp:"倒", py:"dào"},
  {en:"don't", trad:"別", simp:"别", py:"bié"},
  {en:"landlord", trad:"房東", simp:"房东", py:"fángdōng"},
  {en:"tree", trad:"樹", simp:"树", py:"shù"},
  {en:"to collide with; hit; strike", trad:"撞", simp:"撞", py:"zhuàng"},
  {en:"bad", trad:"壞", simp:"坏", py:"huài"},
  {en:"(used at the sentence end to soften the tone)", trad:"呀", simp:"呀", py:"ya"},
  {en:"careful, cautious; to be careful", trad:"小心", simp:"小心", py:"xiǎoxīn"},
  {en:"mirror", trad:"鏡子", simp:"镜子", py:"jìngzi"},
  {en:"broken", trad:"破", simp:"破", py:"pò"},
  {en:"to collaborate by dividing up the work", trad:"分工合作", simp:"分工合作", py:"fēngōnghézuò"},
  {en:"idea", trad:"主意", simp:"主意", py:"zhǔyì"},
  {en:"to be responsible for", trad:"負責", simp:"负责", py:"fùzé"},
  {en:"luggage; baggage", trad:"行李", simp:"行李", py:"xíngli"},
  {en:"to put; place", trad:"放", simp:"放", py:"fàng"},
  {en:"to install, assemble; to load, pack", trad:"裝", simp:"装", py:"zhuāng"},
  {en:"to clean; sweep", trad:"掃", simp:"扫", py:"sǎo"},
  {en:"to arrange; sort out", trad:"整理", simp:"整理", py:"zhěngli"},
  {en:"box; case", trad:"箱子", simp:"箱子", py:"xiāngzi"},
  {en:"clothes", trad:"衣服", simp:"衣服", py:"yīfu"},
  {en:"to hang", trad:"掛", simp:"挂", py:"guà"},
  {en:"tired; get tired of", trad:"累", simp:"累", py:"lèi"},
  {en:"to act as the host; to treat", trad:"請客", simp:"请客", py:"qǐngkè"},
  {en:"dead; to die", trad:"死", simp:"死", py:"sǐ"},
  {en:"nearby", trad:"附近", simp:"附近", py:"fùjìn"},
  {en:"to forget", trad:"忘", simp:"忘", py:"wàng"},
  {en:"door", trad:"門", simp:"门", py:"mén"},
  {en:"window", trad:"窗", simp:"窗", py:"chuāng"},
  {en:"to close (door/window)", trad:"關上", simp:"关上", py:"guānshàng"},
  {en:"coat", trad:"外套", simp:"外套", py:"wàitào"},
  {en:"we; us (when used by the speaker to include him/herself and the person(s) being spoken to)", trad:"咱們", simp:"咱们", py:"zánmen"}
],

// ---- 2-2 (Experiencing Culture and the Arts) ----
"Lesson 2-2": [
  {en:"wall", trad:"牆", simp:"墙", py:"qiáng"},
  {en:"(indicates continuous or stationary status)", trad:"著", simp:"着", py:"zhe"},
  {en:"photograph, picture", trad:"照片", simp:"照片", py:"zhàopiàn"},
  {en:"clothes", trad:"服裝", simp:"服装", py:"fúzhuāng"},
  {en:"(performance) stage", trad:"舞台", simp:"舞台", py:"wŭtái"},
  {en:"to place, put", trad:"擺", simp:"摆", py:"băi"},
  {en:"various, all kinds of", trad:"各種", simp:"各种", py:"gèzhŏng"},
  {en:"musical instrument", trad:"樂器", simp:"乐器", py:"yuèqì"},
  {en:"actor or actress, performer", trad:"演員", simp:"演员", py:"yǎnyuán"},
  {en:"performance / to perform", trad:"表演", simp:"表演", py:"biǎoyăn"},
  {en:"musician", trad:"樂師", simp:"乐师", py:"yuèshī"},
  {en:"to play (the drum); to hit", trad:"打", simp:"打", py:"dă"},
  {en:"drum", trad:"鼓", simp:"鼓", py:"gŭ"},
  {en:"to play (a stringed musical instrument); to pull", trad:"拉", simp:"拉", py:"lā"},
  {en:"two-stringed bowed instruments", trad:"胡琴", simp:"胡琴", py:"húqín"},
  {en:"to play, pluck, strike", trad:"彈奏", simp:"弹奏", py:"tánzòu"},
  {en:"oneself", trad:"自己", simp:"自己", py:"zìjǐ"},
  {en:"measure word (classifier) for Chinese theater performances", trad:"齣", simp:"出", py:"chū"},
  {en:"play, drama", trad:"戲", simp:"戏", py:"xì"},
  {en:"to paint, draw / a painting", trad:"畫", simp:"画", py:"huà"},
  {en:"face", trad:"臉", simp:"脸", py:"liăn"},
  {en:"to hold, take", trad:"拿", simp:"拿", py:"ná"},
  {en:"measure word (classifier) for a utensil with a handle", trad:"把", simp:"把", py:"bă"},
  {en:"knife", trad:"刀", simp:"刀", py:"dāo"},
  {en:"energetic, high-spirited, proud", trad:"神氣", simp:"神气", py:"shénqì"},
  {en:"seat", trad:"座位", simp:"座位", py:"zuòwèi"},
  {en:"full", trad:"滿", simp:"满", py:"măn"},
  {en:"audience", trad:"觀眾", simp:"观众", py:"guānzhòng"},
  {en:"to stand", trad:"站", simp:"站", py:"zhàn"},
  {en:"it's a deal", trad:"一言為定", simp:"一言为定", py:"yì yán wéi dìng"}
]
  }
};

console.log('VOCAB lessons loaded:', Object.keys(window.VOCAB.lessons).slice(-5));